### ISSUE TITLE
Covers not showing up in Library even after updating to 2.1.1

### ISSUE THREAD

**Issue by BaccanoMob** [xgi/houdoku-extensions#4]
![image](https://user-images.githubusercontent.com/82655889/121834856-11dea580-ccd0-11eb-9b60-4402573f46c2.png)

Left is from CatManga and right is from Local import. The covers are visible only inside their respective series.

**Comment by xgi** [comment]
Hmm, I'm having trouble reproducing this - covers from those extensions are displaying for me. I think this is probably actually a client issue with resolving the thumbnail path. It seems the client detects the downloaded thumbnail (otherwise it would use the default thumbnail like shown below) but isn't able to load it for some reason.

- Can you clarify that the covers *do* show on the series page (the one with the chapter list)?
- Can you try opening the console on the library page with ctrl+shift+i, going to the console tab, and then seeing if there are any errors listed?
- Might be a stretch, but can you check that the covers were actually saved to the filesystem? On Windows this would be in `C:\Users\user\AppData\Roaming\Houdoku\thumbnails` by default.

I'll keep trying to see if I can reproduce this somehow. Thanks.

![ex](https://i.imgur.com/eJHPump.png)

**Comment by BaccanoMob** [comment]
1. Yes they do show properly when i open the series.
![image](https://user-images.githubusercontent.com/82655889/121839467-69820e80-ccda-11eb-9a4d-be1ee9a3aaee.png)
![image](https://user-images.githubusercontent.com/82655889/121839483-730b7680-ccda-11eb-9f34-17a12ea163e5.png)

2. Not exactly sure about this, nothing prompting error in "Elements tab" but do you mean "issues" (yellow text bubble), there were 2.

![image](https://user-images.githubusercontent.com/82655889/121840010-8a972f00-ccdb-11eb-8aca-be232f136136.png)

Issues:
-Indicate whether a cookie is intended to be set in cross-site context by specifying its SameSite attribute
-Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute

3. Thumbnails are there in the file location.
![image](https://user-images.githubusercontent.com/82655889/121840103-d21dbb00-ccdb-11eb-83bf-652cdd3d6c8a.png)

**Comment by parointi** [comment]
I have the exact same issue. My series are from catmanga and mangadex. Thumbnails were downloaded in the file location and I got the same two issues (yellow text bubble). I am using a mac.
